build:
    cargo build

gen: build gen-schema

gen-schema:
	START_DIR=$(pwd); \
	for f in ./packages/*; do \
		echo "generating schema"; \
		cd "$f"; \
		CMD="cargo run --example schema"; \
		eval ${CMD} > /dev/null; \
		rm -rf ./schema/raw; \
		cd "$START_DIR"; \
	done

test:
    cargo test

optimize:
    ./optimize.sh

simtest: optimize
    if [[ $(uname -m) =~ "arm64" ]]; then \
        mv ./../artifacts/covenant_depositor-aarch64.wasm ./../artifacts/covenant_depositor.wasm && \
        mv ./../artifacts/covenant_lper-aarch64.wasm ./../artifacts/covenant_lper.wasm && \
        mv ./../artifacts/covenant_ls-aarch64.wasm ./../artifacts/covenant_ls.wasm \
    ;fi

    cp ./astroport/*.wasm ./../artifacts

    mkdir -p tests/interchaintest/wasms

    cp -R ./../artifacts/*.wasm tests/interchaintest/wasms
    go clean -testcache
    cd tests/interchaintest/ && go test -v ./...