build:
    cargo build

gen: build gen-schema

gen-schema:
	START_DIR=$(pwd); \
	for f in ../contracts/*; do \
		echo "generating schema"; \
		cd "$f"; \
		CMD="cargo run --example schema"; \
		eval ${CMD} > /dev/null; \
		rm -rf ./schema/raw; \
		cd "$START_DIR"; \
	done

test:
    cargo test

lint:
	cargo +nightly clippy --all-targets -- -D warnings && cargo +nightly fmt --all --check

optimize:
    ./optimize.sh

simtest: optimize
    if [[ $(uname -m) =~ "arm64" ]]; then \
        mv ./../artifacts/covenant_depositor-aarch64.wasm ./../artifacts/covenant_depositor.wasm && \
        mv ./../artifacts/covenant_lp-aarch64.wasm ./../artifacts/covenant_lp.wasm && \
        mv ./../artifacts/covenant_ls-aarch64.wasm ./../artifacts/covenant_ls.wasm && \
        mv ./../artifacts/covenant_clock-aarch64.wasm ./../artifacts/covenant_clock.wasm && \
        mv ./../artifacts/covenant_holder-aarch64.wasm ./../artifacts/covenant_holder.wasm && \
        mv ./../artifacts/covenant_covenant-aarch64.wasm ./../artifacts/covenant_covenant.wasm \
    ;fi

    cp ./astroport/*.wasm ./../artifacts

    mkdir -p tests/interchaintest/wasms

    cp -R ./../artifacts/*.wasm tests/interchaintest/wasms
    go clean -testcache
    cd tests/interchaintest/ && go test -timeout 30m -v ./...

ictest:
    cd tests/interchaintest/ && go test -timeout 20m -v ./...