[package]
name        = "valence-covenant-swap"
edition     = { workspace = true }
authors     = ["benskey bekauz@protonmail.com"]
description = "Swap covenant contract"
license     = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

exclude = ["contract.wasm", "hash.txt"]


[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema              = { workspace = true }
cosmwasm-std                 = { workspace = true }
cw-storage-plus              = { workspace = true }
cw-utils                     = { workspace = true }
cw2                          = { workspace = true }
serde                        = { workspace = true }
thiserror                    = { workspace = true }
sha2                         = { workspace = true }
neutron-sdk                  = { workspace = true }
cosmos-sdk-proto             = { workspace = true }
schemars                     = { workspace = true }
serde-json-wasm              = { workspace = true }
prost                        = { workspace = true }
prost-types                  = { workspace = true }
bech32                       = { workspace = true }
valence-clock               = { workspace = true, features = ["library"] }
valence-swap-holder         = { workspace = true, features = ["library"] }
covenant-utils               = { workspace = true }
valence-native-splitter     = { workspace = true, features = ["library"] }
valence-ibc-forwarder       = { workspace = true, features = ["library"] }
valence-interchain-router   = { workspace = true, features = ["library"] }
valence-native-router       = { workspace = true, features = ["library"] }
