build:
    cargo build

gen: build gen-schema

gen-schema:
	START_DIR=$(pwd); \
	for f in ./packages/*; do \
		echo "generating schema"; \
		cd "$f"; \
		CMD="cargo run --example schema"; \
		eval ${CMD} > /dev/null; \
		rm -rf ./schema/raw; \
		cd "$START_DIR"; \
	done

test:
    cargo test

lint:
	cargo +nightly clippy --all-targets -- -D warnings && cargo +nightly fmt --all --check

optimize:
    ./optimize.sh

simtest: optimize
    if [[ $(uname -m) =~ "arm64" ]]; then \
        mv ./../artifacts/covenant_ibc_forwarder-aarch64.wasm ./../artifacts/covenant_ibc_forwarder.wasm && \
        mv ./../artifacts/covenant_interchain_router-aarch64.wasm ./../artifacts/covenant_interchain_router.wasm && \
        mv ./../artifacts/covenant_clock-aarch64.wasm ./../artifacts/covenant_clock.wasm && \
        mv ./../artifacts/covenant_two_party_pol_holder-aarch64.wasm ./../artifacts/covenant_two_party_pol_holder.wasm && \
        mv ./../artifacts/covenant_astroport_liquid_pooler-aarch64.wasm ./../artifacts/covenant_liquid_pooler.wasm && \
        mv ./../artifacts/covenant_two_party_pol-aarch64.wasm ./../artifacts/covenant_two_party_pol.wasm \
    ;fi

    mkdir -p tests/interchaintest/wasms
    cp ./astroport/*.wasm ./../artifacts

    cp -R ./../artifacts/*.wasm tests/interchaintest/wasms

    go clean -testcache
    cd tests/interchaintest/ && go test -timeout 30m -v ./...

ictest:
    go clean -testcache
    cd tests/interchaintest/ && go test -timeout 20m -v ./...